# Generated by Django 6.0.5 on 2026-05-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('message_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('guild_id', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('required_role_id', models.CharField(blank=True, max_length=100, null=True)),
                ('host_user_id', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=255)),
                ('winners_count', models.IntegerField(default=1)),
                ('end_time', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GiveawayRoleBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(max_length=100)),
                ('role_id', models.CharField(max_length=100)),
                ('entries', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('guild_id', 'role_id')},
            },
        ),
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('guild_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='UserWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('wins', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('guild_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='GiveawayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.giveaway')),
            ],
            options={
                'unique_together': {('giveaway', 'user_id')},
            },
        ),
    ]
